### ISSUE TITLE
Can't launch shell.py

### ISSUE THREAD

**Issue by Nikki-Devil** [Dibi-programming-langage/Skribi-langage-source#11]
Can't launch shell.py (see screenshot)
Adding src.skribi. to the two imports of skribi_file.py seems to fix this issue

shell.py ne se lance pas (voir screenshot)
Ajouter src.skribi. dans le nom des deux import demandé dans skribi_file.py semble régler ce problème

![Capture d’écran de 2022-05-10 12-14-32](https://user-images.githubusercontent.com/52826088/167607962-83ab558a-80ff-405a-a09d-6933f382c94a.png)

**Comment by Alexiscomete** [comment]
oui j'ai oublié src.skribi. merci !

**Comment by Alexiscomete** [comment]
je ne close pas encore car il faut que je merge avant

**Comment by Nikki-Devil** [comment]
Je peux faire un pr si tu veux pour faciliter

**Comment by Nikki-Devil** [comment]
Corrigé dans la branche expérimentale ([fichier corrigé](https://github.com/Dibi-programming-langage/Skribi-langage-source/blob/Start/src/skribi/skribi_file.py))

**Comment by Alexiscomete** [comment]
:octocat:

**Comment by Alexiscomete** [comment]
fait
